name: TheSuccessFormula
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05759
title: The Success Formula
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#222222'
    - '#575757'
    - '#a4a4a4'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
