typography_spectrum: 0.05759
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#222222'
    - '#575757'
    - '#a4a4a4'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: TheSuccessFormula
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: 'http://danielmerriman.com'
    type: external
favicon: null
title: The Success Formula
purpose: []
